### ISSUE TITLE
Are there any gradle dependencies for modules?

### ISSUE THREAD

**Issue by mohitrajput987** [Acuant/AndroidSDKV11#2]
By looking at the code, I found that there is no gradle dependency to integrate Acuant's v11 SDK into my app.
Assuming we have to download the module's code and integrate it into our app. Is it true or you have your artefacts in JCentre/Maven Central just like old SDK of Acuant?

**Comment by vgargacuant** [comment]
Gradle support is available now. Please review the documentation on https://github.com/Acuant/AndroidSDKV11 for gradle support.
